# Generated by Django 6.0.3 on 2026-03-03 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipos',
            },
        ),
        migrations.CreateModel(
            name='Geladeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_geladeira', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo', models.CharField(max_length=150)),
                ('capacidade', models.PositiveIntegerField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geladeiras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'geladeiras',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('validade', models.DateField(blank=True, null=True)),
                ('botado_em', models.DateTimeField(auto_now_add=True)),
                ('geladeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.geladeira')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='core.tipo')),
            ],
            options={
                'db_table': 'itens',
            },
        ),
    ]
